---
language: node_js
node_js:
  - '0.10.0'
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - npm start &
  - sleep 5s
env:
  global:
  - secure: ! 'VK/JUNjO7SaUmX90fzyeBnBjTlRQNTQ5fmNSWhats2iOSUpaSufYWyz8ZGiHRz63uxAQpLtLsgBLxvZ7qwBtl15nRgNkarG8IOXkpOgVJJHHRi+7LE4cGzvEZ8/nbwW0X/mEmllT8PT5EptHtehtP9DibRpFEKuy24AOfegLZNY='
  - secure: ! 'HFZLyTEXv5r3dRO1iaFkDjXmyVbqn96jtMvH8it2G7wbeHhaOs25AgMreIFa5neJS8ntHUMwaL/4A833JGPvNfDwZnbEShusPnqrv3n8IPvu8jPtb9kxRiuuXLJvVgXV71uCDHBIGRZt+sOhdUwtJ6M3dzwJBniC+WloPz6TUpM='
